language: python

sudo: false

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r vaporwavely/tests/requirements.txt

script: nosetests --with-coverage --cover-package=vaporwavely

after_success: codecov
